# Generated by Django 4.2.7 on 2025-10-27 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuturePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100, verbose_name='预测方法')),
                ('address', models.CharField(max_length=200, verbose_name='地址信息')),
                ('image_url', models.URLField(max_length=500, verbose_name='预测结果图表URL')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '未来预测记录',
                'verbose_name_plural': '未来预测记录',
                'indexes': [models.Index(fields=['method', 'address'], name='backend_fut_method_593808_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClusterAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='地址信息')),
                ('image_url', models.URLField(max_length=500, verbose_name='聚类结果图表URL')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '聚类分析记录',
                'verbose_name_plural': '聚类分析记录',
                'indexes': [models.Index(fields=['address'], name='backend_clu_address_8149e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnomalyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100, verbose_name='分析方法')),
                ('address', models.CharField(max_length=200, verbose_name='地址信息')),
                ('image_url', models.URLField(max_length=500, verbose_name='分析结果图表URL')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '异常分析记录',
                'verbose_name_plural': '异常分析记录',
                'indexes': [models.Index(fields=['method', 'address'], name='backend_ano_method_1449bd_idx')],
            },
        ),
    ]
