/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconContainer: typeof import('./src/components/iconContainer.vue')['default']
    MainPageButton: typeof import('./src/components/MainPageButton.vue')['default']
    NavBox: typeof import('./src/components/navBox.vue')['default']
    NavIcon: typeof import('./src/components/navIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNavigation: typeof import('./src/components/topNavigation.vue')['default']
  }
}
